helmGlobals:
  chartHome: ../../components
helmCharts:
- name: coredns
  releaseName: coredns
  namespace: coredns-system
  version: v1.3.0
  includeCRDs: true
  valuesFile: values.yaml
  additionalValuesFiles:
  - ../../overlays/dev/values.yaml
  
  
